export enum Permissions {
    //Book
    VIEW_BOOK = "VIEW_BOOK",
    ADD_BOOK = "ADD_BOOK",
    UPDATE_BOOK = "UPDATE_BOOK",
    DELETE_BOOK = "DELETE_BOOK",
    ASSIGN_BOOK_TO_CATEGORY = "ASSIGN_BOOK_TO_CATEGORY",
    REMOVE_BOOK_FROM_CATEGORY = "REMOVE_BOOK_FROM_CATEGORY",
    //User
    VIEW_USER = "VIEW_USER",
    ADD_USER = "ADD_USER",
    UPDATE_USER = "UPDATE_USER",
    DELETE_USER = "DELETE_USER",
    //Role
    VIEW_ROLE = "VIEW_ROLE",
    ADD_ROLE = "ADD_ROLE",
    UPDATE_ROLE = "UPDATE_ROLE",
    DELETE_ROLE = "DELETE_ROLE",
    ASSIGN_ROLE_TO_USER = "ASSIGN_USER_TO_ROLE",
    REMOVE_ROLE_FROM_USER = "REMOVE_USER_FROM_ROLE",
    //permission
    VIEW_PERMISSION = "VIEW_PERMISSION",
    ADD_PERMISSION = "ADD_PERMISSION",
    UPDATE_PERMISSION = "UPDATE_PERMISSION",
    DELETE_PERMISSION = "DELETE_PERMISSION",
    ASSIGN_PERMISSION_TO_ROLE = "ASSIGN_PERMISSION",
    REMOVE_PERMISSION_FROM_ROLE = "REMOVE_PERMISSION",
    //Category
    VIEW_CATEGORY = "VIEW_CATEGORY",
    ADD_CATEGORY = "ADD_CATEGORY",
    UPDATE_CATEGORY = "UPDATE_CATEGORY",
    DELETE_CATEGORY = "DELETE_CATEGORY"
}